import AppKit
import Combine

/// The pasteboard surface ClipboardHistory needs, so tests can inject a fake.
@MainActor
protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    var types: [String] { get }
    func string() -> String?
    /// Writes plain text and returns the new change count.
    func write(_ text: String) -> Int
}

@MainActor
final class SystemPasteboard: PasteboardReading {
    private let pasteboard = NSPasteboard.general
    var changeCount: Int { pasteboard.changeCount }
    var types: [String] { pasteboard.types?.map(\.rawValue) ?? [] }
    func string() -> String? { pasteboard.string(forType: .string) }
    func write(_ text: String) -> Int {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        return pasteboard.changeCount
    }
}

struct ClipboardItem: Identifiable, Equatable {
    let id = UUID()
    let text: String
    let copiedAt: Date
    /// Pinned items stay at the top and are never pushed out. Pins live in memory, like the history.
    var pinned = false

    enum Kind: String, CaseIterable {
        case links, emails, numbers, colors, code
        /// Words that ask for this kind after "clip".
        var words: [String] {
            switch self {
            case .links: return ["link", "links", "url", "urls"]
            case .emails: return ["email", "emails"]
            case .numbers: return ["number", "numbers"]
            case .colors: return ["color", "colors", "colour", "colours"]
            case .code: return ["code", "snippet", "snippets"]
            }
        }
    }

    func isKind(_ kind: Kind) -> Bool {
        let value = text.trimmingCharacters(in: .whitespacesAndNewlines)
        switch kind {
        case .links: return value.range(of: #"^(https?://|www\.)\S+$"#, options: .regularExpression) != nil
        case .emails: return value.range(of: #"^[^@\s]+@[^@\s]+\.[a-zA-Z]{2,}$"#, options: .regularExpression) != nil
        case .numbers:
            return value.range(of: #"^[£$€¥]?\s?-?[0-9][0-9.,\s]*%?$"#, options: .regularExpression) != nil
        case .colors:
            return value.range(of: #"^(#[0-9a-fA-F]{3,8}|rgba?\(.*\)|hsla?\(.*\))$"#, options: .regularExpression) != nil
        case .code:
            return value.contains("\n") && value.range(of: #"[{};=()<>]"#, options: .regularExpression) != nil
        }
    }
}

/// In-memory plain-text clipboard history. Nothing is written to disk. Items from
/// password managers and apps that mark data concealed or transient are skipped.
@MainActor
final class ClipboardHistory: ObservableObject {
    static let limit = 50
    static let maxLength = 20_000
    static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"
    ]
    @Published private(set) var items: [ClipboardItem] = []
    private(set) var isEnabled = false
    private let pasteboard: PasteboardReading
    private var lastChangeCount: Int
    private var timer: Timer?

    init(pasteboard: PasteboardReading? = nil) {
        self.pasteboard = pasteboard ?? SystemPasteboard()
        lastChangeCount = self.pasteboard.changeCount
    }

    static func shouldSkip(types: [String]) -> Bool {
        types.contains { skippedTypes.contains($0) }
    }

    func setEnabled(_ enabled: Bool) {
        guard enabled != isEnabled else { return }
        isEnabled = enabled
        timer?.invalidate(); timer = nil
        guard enabled else { items = []; return }
        // Start from the current contents' count so enabling does not import what was copied before.
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func poll(now: Date = Date()) {
        let count = pasteboard.changeCount
        guard isEnabled, count != lastChangeCount else { return }
        lastChangeCount = count
        guard !Self.shouldSkip(types: pasteboard.types), let text = pasteboard.string(),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, text.count <= Self.maxLength else { return }
        let wasPinned = items.contains { $0.text == text && $0.pinned }
        items.removeAll { $0.text == text }
        items.insert(ClipboardItem(text: text, copiedAt: now, pinned: wasPinned), at: 0)
        trim()
    }

    /// Puts an entry back on the pasteboard without recording it as a new copy.
    func restore(_ item: ClipboardItem) {
        lastChangeCount = pasteboard.write(item.text)
    }

    func togglePin(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].pinned.toggle()
        trim()
    }

    /// Unpinned items beyond the limit drop off the end.
    private func trim() {
        var unpinned = 0
        items = items.filter { item in
            if item.pinned { return true }
            unpinned += 1
            return unpinned <= Self.limit
        }
    }

    /// Pinned first, then newest. "links", "numbers", "colours", "emails", and "code" filter by kind.
    func matches(_ filter: String) -> [ClipboardItem] {
        let text = filter.trimmingCharacters(in: .whitespacesAndNewlines)
        let ordered = items.filter(\.pinned) + items.filter { !$0.pinned }
        guard !text.isEmpty else { return ordered }
        if let kind = ClipboardItem.Kind.allCases.first(where: { $0.words.contains(text.lowercased()) }) {
            return ordered.filter { $0.isKind(kind) }
        }
        if ["pinned", "pins", "pin"].contains(text.lowercased()) { return ordered.filter(\.pinned) }
        return ordered.filter { $0.text.localizedCaseInsensitiveContains(text) }
    }

    /// Returns the filter text when `query` asks for clipboard history ("clip", "clipboard", "clip <text>").
    static func filter(for query: String) -> String? {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
        let parts = trimmed.split(separator: " ", maxSplits: 1)
        guard let first = parts.first, ["clip", "clipboard"].contains(first.lowercased()) else { return nil }
        return parts.count > 1 ? String(parts[1]) : ""
    }
}
