import AppKit
import Combine

/// The pasteboard surface ClipboardHistory needs, so tests can inject a fake.
@MainActor
protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    var types: [String] { get }
    func string() -> String?
    /// Writes plain text and returns the new change count.
    func write(_ text: String) -> Int
}

@MainActor
final class SystemPasteboard: PasteboardReading {
    private let pasteboard = NSPasteboard.general
    var changeCount: Int { pasteboard.changeCount }
    var types: [String] { pasteboard.types?.map(\.rawValue) ?? [] }
    func string() -> String? { pasteboard.string(forType: .string) }
    func write(_ text: String) -> Int {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        return pasteboard.changeCount
    }
}

struct ClipboardItem: Identifiable, Equatable {
    let id = UUID()
    let text: String
    let copiedAt: Date
}

/// In-memory plain-text clipboard history. Nothing is written to disk. Items from
/// password managers and apps that mark data concealed or transient are skipped.
@MainActor
final class ClipboardHistory: ObservableObject {
    static let limit = 50
    static let maxLength = 20_000
    static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"
    ]
    @Published private(set) var items: [ClipboardItem] = []
    private(set) var isEnabled = false
    private let pasteboard: PasteboardReading
    private var lastChangeCount: Int
    private var timer: Timer?

    init(pasteboard: PasteboardReading? = nil) {
        self.pasteboard = pasteboard ?? SystemPasteboard()
        lastChangeCount = self.pasteboard.changeCount
    }

    static func shouldSkip(types: [String]) -> Bool {
        types.contains { skippedTypes.contains($0) }
    }

    func setEnabled(_ enabled: Bool) {
        guard enabled != isEnabled else { return }
        isEnabled = enabled
        timer?.invalidate(); timer = nil
        guard enabled else { items = []; return }
        // Start from the current contents' count so enabling does not import what was copied before.
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func poll(now: Date = Date()) {
        let count = pasteboard.changeCount
        guard isEnabled, count != lastChangeCount else { return }
        lastChangeCount = count
        guard !Self.shouldSkip(types: pasteboard.types), let text = pasteboard.string(),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, text.count <= Self.maxLength else { return }
        items.removeAll { $0.text == text }
        items.insert(ClipboardItem(text: text, copiedAt: now), at: 0)
        if items.count > Self.limit { items.removeLast(items.count - Self.limit) }
    }

    /// Puts an entry back on the pasteboard without recording it as a new copy.
    func restore(_ item: ClipboardItem) {
        lastChangeCount = pasteboard.write(item.text)
    }

    func matches(_ filter: String) -> [ClipboardItem] {
        let text = filter.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return items }
        return items.filter { $0.text.localizedCaseInsensitiveContains(text) }
    }

    /// Returns the filter text when `query` asks for clipboard history ("clip", "clipboard", "clip <text>").
    static func filter(for query: String) -> String? {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
        let parts = trimmed.split(separator: " ", maxSplits: 1)
        guard let first = parts.first, ["clip", "clipboard"].contains(first.lowercased()) else { return nil }
        return parts.count > 1 ? String(parts[1]) : ""
    }
}
