import AppKit
import Combine
import LauncherCore

/// Clipboard history. The main thread only reads the change count every 0.5 s, the pasteboard
/// types, and the front app; reading, hashing, encoding, thumbnails, text recognition, and disk
/// work run on `worker`. Items from password managers, ignored apps, and apps that mark data
/// concealed or transient are skipped. Nothing here uses the network.
@MainActor
final class ClipboardHistory: ObservableObject {
    nonisolated static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"
    ]
    /// Newest first.
    @Published private(set) var entries: [ClipEntry] = []
    @Published private(set) var failedDeletions: [URL] = []
    @Published private(set) var indexSaveFailed = false
    @Published private(set) var blobSaveFailed = false
    @Published private(set) var loaded = false
    @Published private(set) var settings = ClipboardSettings()
    var isEnabled: Bool { settings.enabled }
    var storageBytes: Int64 { entries.reduce(0) { $0 + $1.byteSize } }
    /// Lower-case search text per entry, made when the entry changes.
    private(set) var searchKeys: [UUID: String] = [:]

    let worker: ClipboardWorker
    lazy var thumbnails = ClipThumbnails(worker: worker)
    private let pasteboard: PasteboardReading
    private let frontmost: () -> ClipSource?
    private var lastChangeCount: Int
    private var timer: Timer?
    /// Captures run one after another, in the order they were copied.
    private var chain: Task<Void, Never>?
    private var saveTask: Task<Void, Never>?
    private var ocrTasks: [UUID: Task<Void, Never>] = [:]
    private var started = false
    private var generation = 0
    private var lastPrune = Date.distantPast
    /// Deleted entries that ⌘Z can bring back. Their blobs are kept until the undo time ends.
    private var trash: [ClipEntry] = []
    private var trashTask: Task<Void, Never>?

    /// `folder` is where history is kept after restart; nil keeps everything in memory, as tests and snapshots do.
    init(pasteboard: PasteboardReading? = nil, folder: URL? = nil, frontmost: (() -> ClipSource?)? = nil,
         removeItem: @escaping (URL) throws -> Void = { try FileManager.default.removeItem(at: $0) }) {
        self.pasteboard = pasteboard ?? SystemPasteboard()
        self.frontmost = frontmost ?? {
            let app = NSWorkspace.shared.frontmostApplication
            return ClipSource(bundleID: app?.bundleIdentifier, name: app?.localizedName)
        }
        worker = ClipboardWorker(folder: folder, persist: ClipboardSettings().persist, removeItem: removeItem)
        lastChangeCount = self.pasteboard.changeCount
    }

    static func shouldSkip(types: [String]) -> Bool {
        types.contains { skippedTypes.contains($0) }
    }

    /// Kept for callers that only switch recording on and off.
    func setEnabled(_ enabled: Bool) {
        var next = settings; next.enabled = enabled; apply(next)
    }

    func apply(_ next: ClipboardSettings) {
        let previous = settings
        settings = next
        if !next.enabled { generation += 1 }
        if !next.ocr {
            for task in ocrTasks.values { task.cancel() }
            ocrTasks = [:]
        }
        if !next.enabled {
            stopTimer()
            saveTask?.cancel(); saveTask = nil
            trashTask?.cancel()
            for task in ocrTasks.values { task.cancel() }
            ocrTasks = [:]
            do {
                // Turning history off deletes it, on disk too.
                let worker = worker
                entries = []; searchKeys = [:]; trash = []
                thumbnails.removeAll()
                enqueue { await worker.deleteAll() }
            }
            started = false
            return
        }
        if !started {
            started = true
            loaded = false
            let worker = worker, persist = next.persist, generation = generation
            enqueue { [weak self] in
                let loaded = await worker.load()
                await worker.setPersistent(persist, entries: loaded)
                guard let self, self.isEnabled else { return }
                guard self.generation == generation else { self.loaded = true; return }
                // A damaged index may list an ID twice; the first is kept.
                var seen = Set<UUID>()
                self.entries = loaded.sorted { $0.copiedAt > $1.copiedAt }.filter { seen.insert($0.id).inserted }
                self.rebuildKeys()
                self.loaded = true
                self.prune()
            }
            startTimer()
        } else {
            if next.persist != previous.persist {
                let worker = worker
                enqueue { [weak self] in
                    guard let self else { return }
                    await worker.setPersistent(next.persist, entries: self.entries)
                }
            }
            if next.retention != previous.retention { prune() }
        }
    }

    private func startTimer() {
        // Start from the current contents' count so turning on does not record what was copied before.
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }
    private func stopTimer() { timer?.invalidate(); timer = nil }

    private func enqueue(_ work: @escaping @MainActor () async -> Void) {
        let previous = chain
        chain = Task { @MainActor in
            await previous?.value
            await work()
            await self.updateStorageState()
        }
    }

    func updateStorageState() async {
        failedDeletions = await worker.failedDeletions
        indexSaveFailed = await worker.indexSaveFailed
        blobSaveFailed = await worker.blobSaveFailed
    }

    func retryStorageCleanup() {
        enqueue { [weak self] in
            guard let self else { return }
            await self.worker.retryDeletions()
            if self.isEnabled {
                await self.worker.setPersistent(self.settings.persist, entries: self.entries)
                await self.worker.saveIndex(self.entries)
            }
        }
    }

    func removePreview(_ url: URL) async {
        await worker.removePreview(url)
        await updateStorageState()
    }

    /// Waits for queued captures and loads. For tests and snapshots.
    func settle() async {
        while let current = chain {
            await current.value
            if chain == current { break }
        }
    }

    private func sameCapturePolicy(as other: ClipboardSettings) -> Bool {
        settings.recordText == other.recordText && settings.recordRichText == other.recordRichText
            && settings.recordImages == other.recordImages && settings.recordFiles == other.recordFiles
            && settings.ignoredApps == other.ignoredApps
    }

    /// Reads the change count only. A change queues a capture on the worker.
    func poll(now: Date = Date()) {
        if isEnabled, now.timeIntervalSince(lastPrune) >= 60 {
            lastPrune = now
            prune(now: now)
        }
        let count = pasteboard.changeCount
        guard isEnabled, count != lastChangeCount else { return }
        lastChangeCount = count
        guard !Self.shouldSkip(types: pasteboard.types) else { return }
        let source = frontmost()
        guard !settings.ignores(source?.bundleID) else { return }
        let settings = settings, pasteboard = pasteboard, worker = worker, generation = generation
        enqueue { [weak self] in
            guard let self, self.isEnabled, self.generation == generation, self.sameCapturePolicy(as: settings) else { return }
            // The types are checked again on what was read, in case the pasteboard changed.
            guard let raw = await pasteboard.read(limit: ClipboardSettings.maxImageBytes, expected: count),
                  !Self.shouldSkip(types: raw.types) else { return }
            let result = await worker.ingest(raw, source: source, settings: settings, now: now)
            guard self.isEnabled, self.generation == generation, self.sameCapturePolicy(as: settings) else {
                if case .added(let entry) = result { await worker.forget([entry.id]) }
                return
            }
            self.record(result, now: now)
        }
    }

    private func record(_ result: ClipboardWorker.Ingest, now: Date) {
        guard isEnabled else { return }
        switch result {
        case .skipped: return
        case .added(let entry):
            entries.insert(entry, at: 0)
            searchKeys[entry.id] = ClipSearch.key(for: entry)
            recognizeText(entry)
        case .duplicate(let id):
            // A re-copy moves the entry to the top and keeps its pin, also one waiting in the undo trash.
            var entry: ClipEntry
            if let index = entries.firstIndex(where: { $0.id == id }) {
                entry = entries.remove(at: index)
            } else if let index = trash.firstIndex(where: { $0.id == id }) {
                entry = trash.remove(at: index)
            } else { return }
            entry.copiedAt = now
            entries.insert(entry, at: 0)
        }
        prune()
    }

    /// Adds text made in the app, such as a transform result, and puts it on the clipboard.
    @discardableResult
    func addText(_ text: String, now: Date = Date()) async -> ClipEntry? {
        lastChangeCount = pasteboard.write(ClipPayload(string: text))
        guard isEnabled else { return nil }
        let worker = worker, generation = generation, settings = settings
        var added: ClipEntry?
        enqueue { [weak self] in
            guard let self, self.isEnabled, self.generation == generation, self.sameCapturePolicy(as: settings) else { return }
            let result = await worker.ingest(ClipRaw(types: ["public.utf8-plain-text"], string: text),
                                             source: ClipSource(bundleID: AppIdentity.bundleID, name: AppIdentity.name),
                                             settings: settings, now: now)
            guard self.isEnabled, self.generation == generation, self.sameCapturePolicy(as: settings) else {
                if case .added(let entry) = result { await worker.forget([entry.id]) }
                return
            }
            self.record(result, now: now)
            if case .added(let entry) = result { added = entry }
            if case .duplicate(let id) = result { added = self.entries.first { $0.id == id } }
        }
        await settle()
        return added
    }

    /// Demo and test entries with their blobs, newest first.
    func insert(_ made: [(ClipEntry, [String: Data])]) async {
        let worker = worker
        enqueue { [weak self] in
            for (entry, blobs) in made.reversed() {
                if case .added(let added) = await worker.add(entry, blobs: blobs) {
                    self?.entries.insert(added, at: 0)
                    self?.searchKeys[added.id] = ClipSearch.key(for: added)
                }
            }
            self?.entries.sort { $0.copiedAt > $1.copiedAt }
            self?.scheduleSave()
        }
        await settle()
    }

    // MARK: Writing back

    /// Puts entries back on the pasteboard without recording them as a new copy. Several entries
    /// are joined by newlines.
    func restore(_ items: [ClipEntry], plain: Bool = false) async -> Bool {
        let worker = worker, generation = generation
        let payload: ClipPayload?
        if items.count == 1, let item = items.first {
            payload = await worker.payload(for: item, plain: plain)
        } else {
            var full: [UUID: String] = [:]
            for item in items where item.kind.isText {
                guard let text = await worker.fullText(item) else { return false }
                full[item.id] = text
            }
            let joined = ClipSearch.joined(items) { full[$0.id] }
            payload = joined.isEmpty ? nil : ClipPayload(string: joined)
        }
        guard let payload, self.generation == generation else { return false }
        lastChangeCount = pasteboard.write(payload)
        return true
    }

    /// Restore for a launcher row: text in the index goes at once; anything else is read first.
    /// A paste waits for the write.
    func restore(_ item: ClipEntry, paste: Bool = false, target: pid_t? = nil) {
        let target = target ?? NSWorkspace.shared.frontmostApplication?.processIdentifier
        if item.kind.isText, !item.textInBlob, !item.hasRTF, !item.hasHTML, let text = item.text {
            lastChangeCount = pasteboard.write(ClipPayload(string: text))
            if paste { Task { _ = await pasteRestored(to: target) } }
            return
        }
        Task {
            guard await restore([item]) else { return }
            if paste { _ = await pasteRestored(to: target) }
        }
    }

    /// Do not send a delayed paste to a different app or paste a newer clipboard value.
    func pasteRestored(to target: pid_t?) async -> Bool {
        guard AXIsProcessTrusted(), let target, target != getpid() else { return false }
        let expected = lastChangeCount
        try? await Task.sleep(nanoseconds: 180_000_000)
        guard !Task.isCancelled, pasteboard.changeCount == expected,
              NSWorkspace.shared.frontmostApplication?.processIdentifier == target else { return false }
        TextInserter.postPaste()
        return true
    }

    // MARK: Changes

    func togglePin(_ id: UUID) {
        guard let index = entries.firstIndex(where: { $0.id == id }) else { return }
        entries[index].pinned.toggle()
        prune()
    }

    /// Removes entries. ⌘Z within a few seconds brings them back.
    func delete(_ ids: Set<UUID>) {
        let removed = entries.filter { ids.contains($0.id) }
        guard !removed.isEmpty else { return }
        commitTrash()
        entries.removeAll { ids.contains($0.id) }
        trash = removed
        trashTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: 8_000_000_000)
            guard !Task.isCancelled else { return }
            self?.commitTrash()
        }
        scheduleSave()
    }

    var canUndoDelete: Bool { !trash.isEmpty }

    func undoDelete() -> [ClipEntry] {
        trashTask?.cancel()
        let restored = trash
        trash = []
        entries = (entries + restored).sorted { $0.copiedAt > $1.copiedAt }
        rebuildKeys()
        prune()
        return restored
    }

    private func commitTrash() {
        trashTask?.cancel()
        guard !trash.isEmpty else { return }
        let ids = trash.map(\.id)
        trash = []
        for id in ids { ocrTasks.removeValue(forKey: id)?.cancel(); searchKeys[id] = nil }
        let worker = worker
        enqueue { await worker.forget(ids) }
    }

    /// Clears history. Pins stay unless `includingPins`.
    func clear(includingPins: Bool) {
        if started, !loaded {
            enqueue { [weak self] in self?.clear(includingPins: includingPins) }
            return
        }
        generation += 1
        thumbnails.removeAll()
        commitTrash()
        let removed = entries.filter { includingPins || !$0.pinned }.map(\.id)
        entries.removeAll { includingPins || !$0.pinned }
        for id in removed { searchKeys[id] = nil; ocrTasks.removeValue(forKey: id)?.cancel() }
        let worker = worker
        saveTask?.cancel()
        let kept = entries
        enqueue {
            if includingPins { await worker.deleteAll() } else { await worker.forget(removed) }
            await worker.saveIndex(kept)
        }
    }

    /// Applies retention, then saves the index a moment later.
    func prune(now: Date = Date()) {
        let expired = settings.retention.expired(entries, now: now)
        if !expired.isEmpty {
            entries.removeAll { expired.contains($0.id) }
            for id in expired { searchKeys[id] = nil; ocrTasks.removeValue(forKey: id)?.cancel() }
            let worker = worker, ids = Array(expired)
            enqueue { await worker.forget(ids) }
        }
        scheduleSave()
    }

    /// One index write after a burst of changes.
    private func scheduleSave() {
        saveTask?.cancel()
        saveTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: 700_000_000)
            guard !Task.isCancelled, let self else { return }
            self.enqueue { [weak self] in
                guard let self, self.isEnabled else { return }
                await self.worker.saveIndex(self.entries)
            }
        }
    }

    /// Saves now, for tests and quitting.
    func flush() async {
        saveTask?.cancel()
        await settle()
        if isEnabled { await worker.saveIndex(entries) }
        await updateStorageState()
    }

    /// Keep the main actor free so queued Clear/disable operations can finish before termination.
    func prepareForQuit() async {
        stopTimer()
        for task in ocrTasks.values { task.cancel() }
        commitTrash()
        await flush()
    }

    private func rebuildKeys() {
        searchKeys = Dictionary(entries.map { ($0.id, ClipSearch.key(for: $0)) }, uniquingKeysWith: { first, _ in first })
    }

    // MARK: Text in images

    /// Finds text in a copied image on this Mac, at low priority, when the setting allows it.
    /// One image at a time, so a burst of screenshots does not decode many large images at once.
    private func recognizeText(_ entry: ClipEntry) {
        guard settings.ocr, entry.ocrText == nil, entry.isImage else { return }
        let worker = worker, id = entry.id
        let previous = ocrChain
        let task = Task { @MainActor [weak self] in
            await previous?.value
            defer { self?.ocrTasks[id] = nil }
            guard !Task.isCancelled, let data = await worker.imageDataForOCR(entry) else { return }
            let text = await Task.detached(priority: .background) { ClipboardCapture.recognizeText(in: data) }.value
            guard !Task.isCancelled, let self, let text, let index = self.entries.firstIndex(where: { $0.id == id }) else { return }
            self.entries[index].ocrText = text
            self.searchKeys[id] = ClipSearch.key(for: self.entries[index])
            self.scheduleSave()
        }
        ocrTasks[id] = task
        ocrChain = task
    }
    private var ocrChain: Task<Void, Never>?

    /// Waits for text recognition, for tests.
    func settleOCR() async { for task in ocrTasks.values { await task.value } }

    // MARK: Search

    /// Pinned first, then newest, narrowed by the chip and the typed words.
    func matches(_ filter: String, chip: ClipFilter = .all) -> [ClipEntry] {
        ClipSearch.filter(entries, keys: searchKeys, chip: chip, query: ClipQuery.parse(filter))
    }

    /// Returns the filter text when `query` asks for clipboard history ("clip", "clips", "clipboard", "clip <text>").
    static func filter(for query: String) -> String? {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
        let parts = trimmed.split(separator: " ", maxSplits: 1)
        guard let first = parts.first, ["clip", "clips", "clipboard"].contains(first.lowercased()) else { return nil }
        return parts.count > 1 ? String(parts[1]) : ""
    }
}
