import AppKit
import LauncherCore
import XCTest
@testable import JevLauncher

@MainActor final class FakePasteboard: PasteboardReading {
    var changeCount = 0
    var types: [String] = []
    var text: String?
    /// Richer contents for the next read, such as an image or files.
    var raw: ClipRaw?
    var written: ClipPayload?
    var onRead: (() -> Void)?
    func string() -> String? { text }
    func copy(_ text: String, types: [String] = ["public.utf8-plain-text"]) {
        self.text = text; self.types = types; raw = nil; changeCount += 1
    }
    func copy(_ raw: ClipRaw) { self.raw = raw; text = raw.string; types = raw.types; changeCount += 1 }
    func write(_ text: String) -> Int { copy(text); return changeCount }
    func read(limit: Int, expected: Int) async -> ClipRaw? {
        guard changeCount == expected else { return nil }
        let value = raw ?? text.map { ClipRaw(types: types, string: $0) }
        onRead?()
        return value
    }
    func write(_ payload: ClipPayload) -> Int {
        written = payload; text = payload.string; raw = nil; changeCount += 1
        return changeCount
    }
}

@MainActor final class ClipboardHistoryTests: XCTestCase {
    private var folders: [URL] = []

    override func tearDown() {
        for folder in folders { try? FileManager.default.removeItem(at: folder) }
        folders = []
        super.tearDown()
    }

    private func tempFolder() -> URL {
        let url = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("JevClipTests-" + UUID().uuidString)
        folders.append(url)
        return url.appendingPathComponent("Clipboard")
    }

    private func make(_ board: FakePasteboard? = nil, folder: URL? = nil, source: ClipSource? = ClipSource(bundleID: "com.apple.Notes", name: "Notes"),
                      settings: ClipboardSettings = ClipboardSettings()) async -> ClipboardHistory {
        let history = ClipboardHistory(pasteboard: board ?? FakePasteboard(), folder: folder, frontmost: { source })
        var settings = settings
        settings.ocr = false
        history.apply(settings)
        await history.settle()
        return history
    }

    private func copy(_ text: String, _ board: FakePasteboard, _ history: ClipboardHistory, types: [String] = ["public.utf8-plain-text"]) async {
        board.copy(text, types: types); history.poll(); await history.settle()
    }

    static func png(width: Int = 40, height: Int = 30, text: String? = nil) -> Data {
        let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: width, pixelsHigh: height, bitsPerSample: 8, samplesPerPixel: 4,
                                   hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
        NSColor.white.setFill(); NSRect(x: 0, y: 0, width: width, height: height).fill()
        NSColor.systemBlue.setFill(); NSRect(x: 4, y: 4, width: 10, height: 10).fill()
        if let text {
            NSAttributedString(string: text, attributes: [.font: NSFont.boldSystemFont(ofSize: CGFloat(height) * 0.45), .foregroundColor: NSColor.black])
                .draw(at: NSPoint(x: 20, y: CGFloat(height) * 0.25))
        }
        NSGraphicsContext.restoreGraphicsState()
        return rep.representation(using: .png, properties: [:])!
    }

    // MARK: Skip rules

    func testSkipsConcealedTransientAutoGeneratedAndPasswordManagerItems() async {
        for type in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"] {
            XCTAssertTrue(ClipboardHistory.shouldSkip(types: ["public.utf8-plain-text", type]), type)
        }
        XCTAssertFalse(ClipboardHistory.shouldSkip(types: ["public.utf8-plain-text"]))
        let board = FakePasteboard(); let history = await make(board)
        await copy("hunter2", board, history, types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"])
        XCTAssertTrue(history.entries.isEmpty)
    }

    /// A concealed copy made while an earlier capture waits is never read under the earlier copy's check.
    func testConcealedCopyDuringQueuedCaptureIsSkipped() async {
        let board = FakePasteboard(); let history = await make(board)
        board.copy("normal"); history.poll()
        board.copy("hunter2", types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]); history.poll()
        await history.settle()
        XCTAssertFalse(history.entries.contains { $0.text == "hunter2" })
    }

    func testSkipsIgnoredApps() async {
        let board = FakePasteboard()
        let history = await make(board, source: ClipSource(bundleID: "com.bitwarden.desktop", name: "Bitwarden"))
        await copy("secret", board, history)
        XCTAssertTrue(history.entries.isEmpty)
    }

    func testSkipsTooLargeItemsAndSwitchedOffKinds() async {
        let board = FakePasteboard(); let history = await make(board)
        await copy(String(repeating: "a", count: ClipboardSettings.maxTextBytes + 1), board, history)
        var raw = ClipRaw(types: ["public.png"]); raw.imageTooLarge = true
        board.copy(raw); history.poll(); await history.settle()
        XCTAssertTrue(history.entries.isEmpty)

        var settings = ClipboardSettings(); settings.recordImages = false
        let noImages = await make(board, settings: settings)
        board.copy(ClipRaw(types: ["public.png"], image: (Self.png(), "public.png"))); noImages.poll(); await noImages.settle()
        XCTAssertTrue(noImages.entries.isEmpty)
    }

    // MARK: Capture

    func testClassifiesAndRecordsSource() async {
        let board = FakePasteboard(); let history = await make(board)
        await copy("https://example.com/a", board, history)
        await copy("#ff8800", board, history)
        await copy("func a() {\n    let b = 1\n    guard let c else { return }\n}", board, history)
        XCTAssertEqual(history.entries.map(\.kind), [.code, .color, .link])
        XCTAssertEqual(history.entries.first?.language, "Swift")
        XCTAssertEqual(history.entries.first?.sourceName, "Notes")
        XCTAssertEqual(history.entries.last?.linkHost, "example.com")
    }

    func testRichTextKeepsFormattingUnlessPlain() async throws {
        let board = FakePasteboard(); let history = await make(board)
        let rtf = try NSAttributedString(string: "Bold words", attributes: [.font: NSFont.boldSystemFont(ofSize: 12)])
            .data(from: NSRange(location: 0, length: 10), documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf])
        board.copy(ClipRaw(types: ["public.rtf", "public.utf8-plain-text"], string: "Bold words", rtf: rtf)); history.poll(); await history.settle()
        let entry = try XCTUnwrap(history.entries.first)
        XCTAssertEqual(entry.kind, .richText)
        XCTAssertTrue(entry.hasRTF)
        _ = await history.restore([entry])
        XCTAssertEqual(board.written?.data.map(\.type), ["public.rtf"])
        _ = await history.restore([entry], plain: true)
        XCTAssertEqual(board.written?.string, "Bold words")
        XCTAssertTrue(board.written?.data.isEmpty ?? false)
    }

    func testImageCaptureRecordsSizeAndThumbnail() async throws {
        let board = FakePasteboard(); let history = await make(board)
        board.copy(ClipRaw(types: ["public.png"], image: (Self.png(width: 800, height: 600), "public.png"))); history.poll(); await history.settle()
        let entry = try XCTUnwrap(history.entries.first)
        XCTAssertEqual(entry.kind, .image)
        XCTAssertEqual(entry.image?.width, 800)
        XCTAssertEqual(entry.image?.height, 600)
        XCTAssertTrue(entry.hasThumbnail)
        let thumb = await history.worker.thumbnail(for: entry, maxPixels: 512)
        XCTAssertLessThanOrEqual(max(thumb?.width ?? 0, thumb?.height ?? 0), 512)
        let payload = await history.worker.payload(for: entry, plain: false)
        XCTAssertEqual(payload?.data.first?.type, "public.png")
    }

    func testFilesAreReferencedAndClassified() async throws {
        let folder = tempFolder().deletingLastPathComponent()
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let pdf = folder.appendingPathComponent("Report.pdf"), note = folder.appendingPathComponent("Note.txt")
        try Data("%PDF-1.4".utf8).write(to: pdf); try Data("hello".utf8).write(to: note)
        let board = FakePasteboard(); let history = await make(board)
        board.copy(ClipRaw(types: ["public.file-url"], fileURLs: [pdf, note])); history.poll(); await history.settle()
        let entry = try XCTUnwrap(history.entries.first)
        XCTAssertEqual(entry.kind, .files)
        XCTAssertEqual(entry.files.map(\.category), [.pdf, .document])
        XCTAssertEqual(entry.files.first?.size, 8)
        XCTAssertNotNil(entry.files.first?.bookmark)
        XCTAssertEqual(entry.title, "Report.pdf and 1 more")
        XCTAssertTrue(history.matches("note").contains { $0.id == entry.id })
    }

    // MARK: De-duplication

    func testReCopyMovesToTopAndKeepsPin() async throws {
        let board = FakePasteboard(); let history = await make(board)
        await copy("one", board, history); history.poll(); await history.settle()
        await copy("two", board, history)
        history.togglePin(try XCTUnwrap(history.entries.last).id)
        await copy("one", board, history)
        XCTAssertEqual(history.entries.map(\.text), ["one", "two"])
        XCTAssertTrue(history.entries[0].pinned)
    }

    func testRestoreDoesNotAddNewEntry() async throws {
        let board = FakePasteboard(); let history = await make(board)
        await copy("a", board, history); await copy("b", board, history)
        let older = try XCTUnwrap(history.entries.last)
        history.restore(older); history.poll(); await history.settle()
        XCTAssertEqual(board.text, "a")
        XCTAssertEqual(history.entries.compactMap(\.text), ["b", "a"])
    }

    func testMultiSelectJoinsInOrder() async {
        let board = FakePasteboard(); let history = await make(board)
        await copy("first", board, history); await copy("second", board, history)
        let ok = await history.restore([history.entries[1], history.entries[0]])
        XCTAssertTrue(ok)
        XCTAssertEqual(board.text, "first\nsecond")
    }

    // MARK: Retention and clearing

    func testRetentionKeepsPinsAndCount() async throws {
        var settings = ClipboardSettings(); settings.maxItems = 100
        let board = FakePasteboard(); let history = await make(board, settings: settings)
        await copy("pinned", board, history)
        history.togglePin(try XCTUnwrap(history.entries.first).id)
        for index in 0..<105 { await copy("item \(index)", board, history) }
        XCTAssertEqual(history.entries.filter { !$0.pinned }.count, 100)
        XCTAssertTrue(history.entries.contains { $0.pinned && $0.text == "pinned" })
        XCTAssertEqual(history.entries.first?.text, "item 104")
    }

    func testClearKeepsPinsUnlessAsked() async throws {
        let board = FakePasteboard(); let history = await make(board)
        await copy("a", board, history); await copy("b", board, history)
        history.togglePin(try XCTUnwrap(history.entries.first).id)
        history.clear(includingPins: false)
        XCTAssertEqual(history.entries.compactMap(\.text), ["b"])
        history.clear(includingPins: true)
        XCTAssertTrue(history.entries.isEmpty)
    }

    func testDeleteCanBeUndone() async {
        let board = FakePasteboard(); let history = await make(board)
        await copy("a", board, history); await copy("b", board, history)
        history.delete([history.entries[0].id])
        XCTAssertEqual(history.entries.compactMap(\.text), ["a"])
        XCTAssertTrue(history.canUndoDelete)
        _ = history.undoDelete()
        XCTAssertEqual(history.entries.compactMap(\.text), ["b", "a"])
    }

    func testDisablingClearsAndIgnoresCopies() async {
        let board = FakePasteboard(); let history = await make(board)
        await copy("a", board, history)
        history.setEnabled(false); await history.settle()
        XCTAssertTrue(history.entries.isEmpty)
        await copy("b", board, history)
        XCTAssertTrue(history.entries.isEmpty)
    }

    // MARK: Persistence

    func testPersistenceRoundTripWithPrivatePermissions() async throws {
        let folder = tempFolder()
        let board = FakePasteboard()
        let first = await make(board, folder: folder)
        await copy("kept after restart", board, first)
        board.copy(ClipRaw(types: ["public.png"], image: (Self.png(), "public.png"))); first.poll(); await first.settle()
        first.togglePin(try XCTUnwrap(first.entries.last).id)
        await first.flush()

        let attributes = try FileManager.default.attributesOfItem(atPath: folder.path)
        XCTAssertEqual((attributes[.posixPermissions] as? NSNumber)?.intValue, 0o700)
        let index = try FileManager.default.attributesOfItem(atPath: folder.appendingPathComponent("index.json").path)
        XCTAssertEqual((index[.posixPermissions] as? NSNumber)?.intValue, 0o600)

        let second = await make(FakePasteboard(), folder: folder)
        XCTAssertEqual(second.entries.map(\.kind), [.image, .text])
        XCTAssertTrue(second.entries[1].pinned)
        let payload = await second.worker.payload(for: second.entries[0], plain: false)
        XCTAssertNotNil(payload?.data.first)
    }

    func testMemoryOnlyModeDeletesTheFolder() async throws {
        let folder = tempFolder()
        let board = FakePasteboard()
        let history = await make(board, folder: folder)
        await copy("first", board, history)
        await history.flush()
        XCTAssertTrue(FileManager.default.fileExists(atPath: folder.path))
        // An image still being captured when the switch changes keeps its data.
        board.copy(ClipRaw(types: ["public.png"], image: (Self.png(), "public.png"))); history.poll()
        var settings = history.settings; settings.persist = false
        history.apply(settings); await history.settle()
        XCTAssertFalse(FileManager.default.fileExists(atPath: folder.path))
        // The image is still there to paste, from memory.
        let payload = await history.worker.payload(for: history.entries[0], plain: false)
        XCTAssertNotNil(payload?.data.first)
        await copy("memory", board, history)
        await history.flush()
        XCTAssertFalse(FileManager.default.fileExists(atPath: folder.path))
    }

    func testClearRejectsQueuedCopyAndPersistsImmediately() async throws {
        let board = FakePasteboard(), folder = tempFolder()
        let history = await make(board, folder: folder)
        await copy("stored secret", board, history)
        await history.flush()
        board.copy("queued secret"); history.poll()
        history.clear(includingPins: true)
        await history.settle()
        XCTAssertTrue(history.entries.isEmpty)
        let reopened = await make(folder: folder)
        XCTAssertTrue(reopened.entries.isEmpty)
    }

    func testClearDuringReadCannotRestorePrivateBlob() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        let history = await make(board, folder: folder)
        board.onRead = { history.clear(includingPins: true) }
        board.copy(String(repeating: "private", count: 1000))
        history.poll(); await history.settle()
        board.onRead = nil
        XCTAssertTrue(history.entries.isEmpty)
        let names = try FileManager.default.contentsOfDirectory(atPath: folder.path)
        XCTAssertFalse(names.contains { UUID(uuidString: $0) != nil })
        let reopened = await make(folder: folder)
        XCTAssertTrue(reopened.entries.isEmpty)
    }

    func testDisabledStartupDeletesExistingHistory() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        let history = await make(board, folder: folder)
        await copy("stored secret", board, history)
        await history.flush()
        var settings = ClipboardSettings(); settings.enabled = false
        let disabled = await make(folder: folder, settings: settings)
        await disabled.flush()
        XCTAssertFalse(FileManager.default.fileExists(atPath: folder.path))
        XCTAssertTrue(disabled.entries.isEmpty)
    }

    func testOffOnDoesNotRecordQueuedCopies() async {
        let board = FakePasteboard()
        let capturing = await make(board)
        board.copy("queued secret"); capturing.poll()
        capturing.setEnabled(false); capturing.setEnabled(true)
        await capturing.settle()
        XCTAssertTrue(capturing.entries.isEmpty)
    }

    func testMemoryOnlyStartupKeepsLoadedTextAndBlobs() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        let history = await make(board, folder: folder)
        let long = String(repeating: "private ", count: 2000)
        await copy(long, board, history); await history.flush()
        var settings = ClipboardSettings(); settings.persist = false
        let memory = await make(folder: folder, settings: settings)
        let entry = try XCTUnwrap(memory.entries.first)
        let restored = await memory.worker.fullText(entry)
        XCTAssertEqual(restored, long)
        XCTAssertFalse(FileManager.default.fileExists(atPath: folder.path))
    }

    func testClearDuringLoadKeepsOnlyPins() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        let original = await make(board, folder: folder)
        await copy("pin", board, original)
        original.togglePin(try XCTUnwrap(original.entries.first).id)
        await copy("remove", board, original); await original.flush()
        let loading = ClipboardHistory(pasteboard: FakePasteboard(), folder: folder)
        var settings = ClipboardSettings(); settings.ocr = false
        loading.apply(settings)
        loading.clear(includingPins: false)
        await loading.settle()
        XCTAssertEqual(loading.entries.compactMap(\.text), ["pin"])
        let reopened = await make(folder: folder)
        XCTAssertEqual(reopened.entries.compactMap(\.text), ["pin"])
    }

    func testRichCopiesWithDifferentFormattingAreDistinct() async {
        let board = FakePasteboard()
        let capture = await make(board)
        await copy("same", board, capture)
        for formatting in ["bold", "italic"] {
            board.copy(ClipRaw(types: ["public.rtf"], string: "same", rtf: Data(formatting.utf8)))
            capture.poll(); await capture.settle()
        }
        XCTAssertEqual(capture.entries.count, 3)
    }

    func testIdlePollExpiresOldEntries() async {
        let board = FakePasteboard(); let history = await make(board)
        await copy("old", board, history)
        history.poll(now: Date().addingTimeInterval(31 * 86_400))
        await history.settle()
        XCTAssertTrue(history.entries.isEmpty)
    }

    func testAddTextWhileDisabledDoesNotStoreBlob() async {
        let folder = tempFolder()
        var settings = ClipboardSettings(); settings.enabled = false
        let history = await make(folder: folder, settings: settings)
        let added = await history.addText(String(repeating: "secret", count: 5000))
        await history.flush()
        XCTAssertNil(added)
        XCTAssertFalse(FileManager.default.fileExists(atPath: folder.path))
    }

    func testLongTextSizeCountsBlobOnce() {
        let text = String(repeating: "a", count: ClipEntry.indexTextLimit + 1)
        let made = ClipboardCapture.text(text, source: nil, now: Date())
        XCTAssertEqual(made.entry.byteSize, Int64(text.utf8.count))
    }

    func testMissingIndexPrunesOrphanBlobs() throws {
        let folder = tempFolder(), id = UUID()
        let store = ClipboardStore(folder: folder)
        store.write([ClipEntry.Blob.text: Data("secret".utf8)], for: id)
        XCTAssertTrue(store.loadIndex().isEmpty)
        XCTAssertNil(store.read(ClipEntry.Blob.text, for: id))
    }

    func testDeletionRetriesOnceAndTreatsMissingFilesAsSuccess() throws {
        let folder = tempFolder(), id = UUID()
        var attempts = 0
        let store = ClipboardStore(folder: folder, removeItem: { url in
            attempts += 1
            if attempts == 1 { throw CocoaError(.fileWriteNoPermission) }
            try FileManager.default.removeItem(at: url)
        })
        store.write([ClipEntry.Blob.text: Data("secret".utf8)], for: id)
        store.delete([id])
        XCTAssertEqual(attempts, 2)
        XCTAssertTrue(store.failedDeletions.isEmpty)
        store.delete([id])
        XCTAssertTrue(store.failedDeletions.isEmpty)
    }

    func testFailedClearIsVisibleAndRetryPreservesNewMemoryEntries() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        var deny = true
        var attempts = 0
        let history = ClipboardHistory(pasteboard: board, folder: folder, removeItem: { url in
            if url.standardizedFileURL == folder.standardizedFileURL {
                attempts += 1
                if deny { throw CocoaError(.fileWriteNoPermission) }
            }
            try FileManager.default.removeItem(at: url)
        })
        var settings = ClipboardSettings(); settings.ocr = false
        history.apply(settings); await history.settle()
        await copy("secret", board, history); await history.flush()
        history.clear(includingPins: true); await history.settle()
        XCTAssertEqual(attempts, 2)
        XCTAssertEqual(history.failedDeletions, [folder])
        XCTAssertTrue(history.entries.isEmpty)
        let persistent = await history.worker.isPersistent
        XCTAssertFalse(persistent)
        await copy(String(repeating: "new", count: 4000), board, history)
        let newEntry = try XCTUnwrap(history.entries.first)
        deny = false
        history.retryStorageCleanup(); await history.settle()
        XCTAssertTrue(history.failedDeletions.isEmpty)
        let payload = await history.worker.payload(for: newEntry, plain: true)
        XCTAssertEqual(payload?.string, String(repeating: "new", count: 4000))
        let reopened = await make(folder: folder)
        XCTAssertEqual(reopened.entries.map(\.id), [newEntry.id])
    }

    func testFailedDisableRemainsVisibleWhileOff() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        var deny = true
        let history = ClipboardHistory(pasteboard: board, folder: folder, removeItem: { url in
            if url.standardizedFileURL == folder.standardizedFileURL && deny { throw CocoaError(.fileWriteNoPermission) }
            try FileManager.default.removeItem(at: url)
        })
        history.apply(ClipboardSettings()); await history.settle()
        await copy("secret", board, history); await history.flush()
        history.setEnabled(false); await history.settle()
        XCTAssertFalse(history.isEnabled)
        XCTAssertEqual(history.failedDeletions, [folder])
        XCTAssertTrue(FileManager.default.fileExists(atPath: folder.path))
        deny = false
        history.retryStorageCleanup(); await history.settle()
        XCTAssertTrue(history.failedDeletions.isEmpty)
        XCTAssertFalse(FileManager.default.fileExists(atPath: folder.path))
    }

    func testFailedMemoryOnlyCleanupKeepsFailureAndBlobs() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        let history = ClipboardHistory(pasteboard: board, folder: folder, removeItem: { url in
            if url.standardizedFileURL == folder.standardizedFileURL { throw CocoaError(.fileWriteNoPermission) }
            try FileManager.default.removeItem(at: url)
        })
        history.apply(ClipboardSettings()); await history.settle()
        let text = String(repeating: "private", count: 2000)
        await copy(text, board, history); await history.flush()
        var settings = history.settings; settings.persist = false
        history.apply(settings); await history.settle()
        XCTAssertEqual(history.failedDeletions, [folder])
        let entry = try XCTUnwrap(history.entries.first)
        let restored = await history.worker.fullText(entry)
        XCTAssertEqual(restored, text)
        await copy("another", board, history)
        XCTAssertEqual(history.failedDeletions, [folder], "Unrelated work must not dismiss the warning")
    }

    func testOrphanAndPreviewDeletionFailuresAreReported() {
        let folder = tempFolder(), id = UUID()
        let store = ClipboardStore(folder: folder, removeItem: { _ in throw CocoaError(.fileWriteNoPermission) })
        store.write([ClipEntry.Blob.text: Data("secret".utf8)], for: id)
        XCTAssertTrue(store.loadIndex().isEmpty)
        XCTAssertEqual(store.failedDeletions.count, 1)
        store.removePreviewFiles()
        XCTAssertEqual(store.failedDeletions.count, 2)
    }

    func testMissingLongTextDoesNotCopyTruncatedText() async {
        let board = FakePasteboard(), history = await make()
        let made = ClipboardCapture.text(String(repeating: "x", count: 20_000), source: nil, now: Date())
        await history.insert([(made.entry, [:])])
        let text = await history.worker.fullText(made.entry)
        XCTAssertNil(text)
        let copied = await history.restore([made.entry])
        XCTAssertFalse(copied)
        let other = await make(board)
        await copy("short", board, other)
        let multiple = await other.restore(other.entries + [made.entry])
        XCTAssertFalse(multiple)
        XCTAssertEqual(board.text, "short")
    }

    func testIndexWriteFailureIsVisibleAndCanRecover() async throws {
        let folder = tempFolder()
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let index = folder.appendingPathComponent("index.json")
        try FileManager.default.createDirectory(at: index, withIntermediateDirectories: true)
        let history = await make(folder: folder)
        await history.flush()
        XCTAssertTrue(history.indexSaveFailed)
        try FileManager.default.removeItem(at: index)
        history.retryStorageCleanup(); await history.settle()
        XCTAssertFalse(history.indexSaveFailed)
    }

    func testWorkerResolvesExistingFilesAndOmitsMissingFiles() async throws {
        let folder = tempFolder()
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let url = folder.appendingPathComponent("file.txt")
        try Data("text".utf8).write(to: url)
        let worker = ClipboardWorker(folder: nil, persist: false)
        let urls = await worker.resolveFiles([ClipFile(path: url.path, name: "file.txt", category: .document),
                                               ClipFile(path: folder.appendingPathComponent("missing").path, name: "missing", category: .other)])
        XCTAssertEqual(urls, [url])
    }

    func testMemoryWorkersHaveSeparatePreviewFiles() async throws {
        let first = ClipboardWorker(folder: nil, persist: false)
        let second = ClipboardWorker(folder: nil, persist: false)
        let made = try XCTUnwrap(ClipboardCapture.image(Self.png(), uti: "public.png", source: nil, now: Date()))
        _ = await first.add(made.entry, blobs: made.blobs)
        let preview = await first.quickLookURL(for: made.entry)
        let url = try XCTUnwrap(preview)
        defer { try? FileManager.default.removeItem(at: url.deletingLastPathComponent()) }
        XCTAssertNotEqual(url.deletingLastPathComponent(), ClipboardStore.previewFolder)
        _ = await second.load()
        await second.deleteAll()
        XCTAssertTrue(FileManager.default.fileExists(atPath: url.path))
        await first.removePreview(url)
        XCTAssertFalse(FileManager.default.fileExists(atPath: url.path))
    }

    func testQuitWaitsForDisableCleanupAndCommitsUndoTrash() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        let history = await make(board, folder: folder)
        await copy(String(repeating: "secret", count: 2000), board, history)
        await history.flush()
        history.delete([try XCTUnwrap(history.entries.first).id])
        await history.prepareForQuit()
        let children = try FileManager.default.contentsOfDirectory(atPath: folder.path)
        XCTAssertFalse(children.contains { UUID(uuidString: $0) != nil })
        history.setEnabled(false)
        await history.prepareForQuit()
        XCTAssertFalse(FileManager.default.fileExists(atPath: folder.path))
    }

    func testFailedBlobWriteDoesNotPublishBrokenEntry() async throws {
        let folder = tempFolder(), board = FakePasteboard()
        let history = await make(board, folder: folder)
        try FileManager.default.createDirectory(at: folder.deletingLastPathComponent(), withIntermediateDirectories: true)
        // A file where the history directory belongs makes writes fail without relying on process permissions.
        try Data("block writes".utf8).write(to: folder)
        await copy(String(repeating: "private", count: 2000), board, history)
        XCTAssertTrue(history.entries.isEmpty)
        XCTAssertTrue(history.blobSaveFailed)
        try FileManager.default.removeItem(at: folder)
        await copy(String(repeating: "private", count: 2000), board, history)
        XCTAssertEqual(history.entries.count, 1, "A failed write must not enter the duplicate cache")
        XCTAssertFalse(history.blobSaveFailed)
    }

    func testFailedPersistenceTransitionKeepsMemoryBlobs() throws {
        let folder = tempFolder(), store = ClipboardStore(folder: nil)
        let made = ClipboardCapture.text(String(repeating: "private", count: 2000), source: nil, now: Date())
        store.write(made.blobs, for: made.entry.id)
        try FileManager.default.createDirectory(at: folder.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data("block writes".utf8).write(to: folder)
        store.goPersistent(folder, entries: [made.entry])
        XCTAssertNil(store.folder)
        XCTAssertTrue(store.blobSaveFailed)
        XCTAssertEqual(store.read(ClipEntry.Blob.text, for: made.entry.id), made.blobs[ClipEntry.Blob.text])
        store.goPersistent(folder, entries: [made.entry])
        XCTAssertEqual(store.folder, folder)
        XCTAssertFalse(store.blobSaveFailed)
        XCTAssertEqual(store.read(ClipEntry.Blob.text, for: made.entry.id), made.blobs[ClipEntry.Blob.text])
    }

    func testMemoryTransitionDoesNotResaveFailedDeletedBlobs() throws {
        let folder = tempFolder(), removed = UUID(), kept = UUID()
        var deny = true
        let store = ClipboardStore(folder: folder, removeItem: { url in
            if deny { throw CocoaError(.fileWriteNoPermission) }
            try FileManager.default.removeItem(at: url)
        })
        store.write([ClipEntry.Blob.text: Data("remove".utf8)], for: removed)
        store.write([ClipEntry.Blob.text: Data("keep".utf8)], for: kept)
        store.delete([removed])
        store.goMemoryOnly(ids: [kept])
        XCTAssertNil(store.read(ClipEntry.Blob.text, for: removed))
        XCTAssertNotNil(store.read(ClipEntry.Blob.text, for: kept))
        deny = false
        store.retryDeletions()
        store.goPersistent(folder, entries: [])
        XCTAssertNil(store.read(ClipEntry.Blob.text, for: removed))
        XCTAssertNotNil(store.read(ClipEntry.Blob.text, for: kept))
    }

    // MARK: Search and transforms

    func testSearchFindsTextInImages() async throws {
        let history = await make()
        var image = ClipboardCapture.image(Self.png(), uti: "public.png", source: nil, now: Date())!
        image.entry.ocrText = "Quarterly Revenue"
        await history.insert([(image.entry, image.blobs)])
        XCTAssertEqual(history.matches("revenue").map(\.id), [image.entry.id])
        XCTAssertEqual(history.matches("images").count, 1)
        XCTAssertEqual(history.matches("", chip: .links).count, 0)
    }

    func testTransformAddsNewEntryAndKeepsOriginal() async throws {
        let board = FakePasteboard(); let history = await make(board)
        await copy("hello", board, history)
        let original = try XCTUnwrap(history.entries.first)
        let added = await history.addText(try ClipTransform.uppercase.apply(original.text ?? ""))
        XCTAssertEqual(added?.text, "HELLO")
        XCTAssertEqual(board.text, "HELLO")
        XCTAssertEqual(history.entries.compactMap(\.text), ["HELLO", "hello"])
        history.poll(); await history.settle()
        XCTAssertEqual(history.entries.count, 2, "the app's own copy is not recorded twice")
    }

    func testRecognizesTextInImageOnDevice() throws {
        let data = Self.png(width: 900, height: 160, text: "HELLO JEVCAST")
        let text = ClipboardCapture.recognizeText(in: data)
        XCTAssertTrue(text?.uppercased().contains("HELLO") ?? false, text ?? "nil")
    }

    func testQueryFilterParsing() {
        XCTAssertEqual(ClipboardHistory.filter(for: "clip"), "")
        XCTAssertEqual(ClipboardHistory.filter(for: "clips"), "")
        XCTAssertEqual(ClipboardHistory.filter(for: "Clipboard "), "")
        XCTAssertEqual(ClipboardHistory.filter(for: "clip invoice 42"), "invoice 42")
        XCTAssertNil(ClipboardHistory.filter(for: "clipper"))
    }
}
