import Foundation

// Shared contract between the app, the background runner, and tests.
// Every type here is plain data: Codable, Equatable, Sendable, no I/O.

/// A scheduled piece of background work. Stored as `Automations/<id>/automation.json`.
public struct Automation: Codable, Equatable, Identifiable, Sendable {
    public static let formatVersion = 1
    public var version = Automation.formatVersion
    /// Generated by code, `[a-z0-9-]`, 1...64 characters. See `AutomationID.isValid`.
    public var id: String
    public var name: String
    /// SF Symbol name for rows and alerts.
    public var symbol: String
    public var kind: Kind
    public var schedule: Schedule
    public var policy: Policy
    public var enabled: Bool
    /// Increases on every saved edit. A run records the revision it started from.
    public var revision: Int
    public var created: Date
    public var updated: Date
    /// Where this came from when imported, for example a Codex automation.
    public var source: ImportSource?
    public var notes: String

    public init(id: String, name: String, symbol: String = "gearshape.2", kind: Kind, schedule: Schedule,
                policy: Policy = Policy(), enabled: Bool = false, revision: Int = 1, created: Date = Date(),
                source: ImportSource? = nil, notes: String = "") {
        self.id = id; self.name = name; self.symbol = symbol; self.kind = kind; self.schedule = schedule
        self.policy = policy; self.enabled = enabled; self.revision = revision; self.created = created
        self.updated = created; self.source = source; self.notes = notes
    }

    public enum Kind: Codable, Equatable, Sendable {
        /// A command the user wrote. Never text from a model.
        case script(ScriptTask)
        /// A prompt run by a signed-in CLI.
        case agent(AgentTask)
        /// Run the script; only when it fails, ask the agent to diagnose and write a short report.
        case scriptWithDiagnosis(ScriptTask, AgentTask)

        public var title: String {
            switch self {
            case .script: return "Script"
            case .agent: return "Agent"
            case .scriptWithDiagnosis: return "Script with diagnosis"
            }
        }
    }

    public struct ImportSource: Codable, Equatable, Sendable {
        public enum App: String, Codable, Sendable { case codex, legacyTasks }
        public var app: App
        public var sourceID: String
        public var path: String
        /// SHA-256 hex of the source file when imported, to show when the source changed.
        public var hash: String
        public init(app: App, sourceID: String, path: String, hash: String) {
            self.app = app; self.sourceID = sourceID; self.path = path; self.hash = hash
        }
    }
}

public enum AutomationID {
    public static func isValid(_ id: String) -> Bool {
        (1...64).contains(id.count) && id.allSatisfy { ("a"..."z").contains($0) || ("0"..."9").contains($0) || $0 == "-" }
            && !id.hasPrefix("-")
    }
    /// A readable, unique ID from a name: "Desktop tidy" → "desktop-tidy-3f9a".
    public static func make(from name: String, suffix: String = String(UUID().uuidString.prefix(4)).lowercased()) -> String {
        let slug = name.lowercased().map { ("a"..."z").contains($0) || ("0"..."9").contains($0) ? $0 : "-" }
        let collapsed = String(slug).split(separator: "-").joined(separator: "-").prefix(48)
        let base = collapsed.isEmpty ? "automation" : String(collapsed)
        return base + "-" + suffix.lowercased().filter { ("a"..."z").contains($0) || ("0"..."9").contains($0) }
    }
}

// MARK: Tasks

public struct ScriptTask: Codable, Equatable, Sendable {
    /// Absolute path of the program. Resolved when the user saves, because launchd has a short PATH.
    public var executable: String
    public var arguments: [String]
    public var workingDirectory: String
    /// Extra environment values. Secret values live in the Keychain; see `secretNames`.
    public var environment: [String: String]
    /// Names of Keychain-held values passed as environment variables to this process only.
    public var secretNames: [String]
    public init(executable: String, arguments: [String] = [], workingDirectory: String,
                environment: [String: String] = [:], secretNames: [String] = []) {
        self.executable = executable; self.arguments = arguments; self.workingDirectory = workingDirectory
        self.environment = environment; self.secretNames = secretNames
    }
    /// One line for rows: "bun scripts/x.ts --client a".
    public var commandLine: String {
        ([URL(fileURLWithPath: executable).lastPathComponent] + arguments.map { $0.contains(" ") ? "\"\($0)\"" : $0 }).joined(separator: " ")
    }
}

public enum AgentRunner: String, Codable, CaseIterable, Sendable {
    case codex, claude
    public var title: String { self == .codex ? "Codex (ChatGPT)" : "Claude" }
    public var executableName: String { rawValue }
}

/// How much an agent may touch. Enforced by the CLI's own OS sandbox (Codex) or tool list (Claude),
/// never by prompt text. There is no full-access level.
public enum AgentAccess: String, Codable, CaseIterable, Sendable {
    /// Reads files. No writes, no network from commands. The default.
    case readOnly
    /// May also edit files inside its working folder and allowed roots.
    case workspaceWrite
    /// May edit its folder and use the network, for reports that call live APIs.
    case workspaceWriteNetwork
    public var title: String {
        switch self {
        case .readOnly: return "Read only"
        case .workspaceWrite: return "Edit its folder"
        case .workspaceWriteNetwork: return "Edit its folder and use the network"
        }
    }
    public var canWrite: Bool { self != .readOnly }
    public var usesNetwork: Bool { self == .workspaceWriteNetwork }
}

public enum ReasoningEffort: String, Codable, CaseIterable, Sendable {
    case none, low, medium, high, xhigh, max
    public var title: String {
        switch self {
        case .none: return "None"; case .low: return "Low"; case .medium: return "Medium"
        case .high: return "High"; case .xhigh: return "Extra high"; case .max: return "Max"
        }
    }
}

public enum OutputMode: String, Codable, CaseIterable, Sendable {
    /// A Markdown report.
    case report
    /// A list of file changes for the user to approve. See `Proposal`.
    case proposal
    /// A report, but the agent may stop to ask the user a question first.
    case ask
    public var title: String {
        switch self { case .report: return "Report"; case .proposal: return "Changes to approve"; case .ask: return "Report, may ask me" }
    }
}

public struct AgentTask: Codable, Equatable, Sendable {
    public var runner: AgentRunner
    public var prompt: String
    /// Model ID passed to the CLI. Empty uses the CLI's own default.
    public var model: String
    public var effort: ReasoningEffort
    /// The faster service tier. Only sent when the runner supports it.
    public var fast: Bool
    public var workingDirectory: String
    /// Extra folders the agent may read. Proposal paths must also sit inside one of these or the working folder.
    public var allowedRoots: [String]
    public var access: AgentAccess
    public var output: OutputMode
    public init(runner: AgentRunner = .codex, prompt: String, model: String = "", effort: ReasoningEffort = .medium,
                fast: Bool = false, workingDirectory: String, allowedRoots: [String] = [], access: AgentAccess = .readOnly,
                output: OutputMode = .report) {
        self.runner = runner; self.prompt = prompt; self.model = model; self.effort = effort; self.fast = fast
        self.workingDirectory = workingDirectory; self.allowedRoots = allowedRoots; self.access = access; self.output = output
    }
}

// MARK: Schedule and policy

public struct Schedule: Codable, Equatable, Sendable {
    public enum Rule: Codable, Equatable, Sendable {
        /// RFC 5545 subset: FREQ=HOURLY|DAILY|WEEKLY, INTERVAL, BYDAY, BYHOUR, BYMINUTE. Stored without the "RRULE:" prefix.
        case rrule(String)
        case once(Date)
        /// Only when asked (Run Now).
        case manual
    }
    public var rule: Rule
    /// IANA time zone for local-time rules.
    public var timeZone: String
    /// Phase for hourly intervals and the earliest possible occurrence.
    public var anchor: Date
    public init(rule: Rule, timeZone: String = TimeZone.current.identifier, anchor: Date = Date()) {
        self.rule = rule; self.timeZone = timeZone; self.anchor = anchor
    }
}

public enum CatchUp: String, Codable, CaseIterable, Sendable {
    /// Missed runs are dropped. The default.
    case skip
    /// After sleep or shutdown, run once for everything missed.
    case runOnce
    public var title: String { self == .skip ? "Skip missed runs" : "Run once after missing" }
}

public struct Policy: Codable, Equatable, Sendable {
    /// Seconds. The process group is stopped after this.
    public var timeout: Int
    /// Extra attempts after a transient failure. Scripts default to 0.
    public var retries: Int
    public var catchUp: CatchUp
    /// Alert when a run fails after its retries. Input and approval always alert.
    public var alertOnFailure: Bool
    /// Also alert when a run succeeds. Off by default; background work stays silent.
    public var alertOnSuccess: Bool
    /// Runs kept on disk for this automation.
    public var keepRuns: Int
    /// Automations with the same lock name never run at the same time, for example "docs-metrics".
    public var sharedLock: String?
    public init(timeout: Int = 1200, retries: Int = 0, catchUp: CatchUp = .skip, alertOnFailure: Bool = true,
                alertOnSuccess: Bool = false, keepRuns: Int = 50, sharedLock: String? = nil) {
        self.timeout = timeout; self.retries = retries; self.catchUp = catchUp; self.alertOnFailure = alertOnFailure
        self.alertOnSuccess = alertOnSuccess; self.keepRuns = keepRuns; self.sharedLock = sharedLock
    }
}

// MARK: Runs

public enum RunState: String, Codable, CaseIterable, Sendable {
    case queued, running, retryWaiting, needsInput, needsApproval, applying
    case succeeded, failed, cancelled, interrupted, rejected, expired
    public var isFinished: Bool { [.succeeded, .failed, .cancelled, .interrupted, .rejected, .expired].contains(self) }
    public var needsUser: Bool { self == .needsInput || self == .needsApproval }
    public var isActive: Bool { [.queued, .running, .retryWaiting, .applying].contains(self) }
    public var title: String {
        switch self {
        case .queued: return "Queued"; case .running: return "Running"; case .retryWaiting: return "Waiting to retry"
        case .needsInput: return "Needs an answer"; case .needsApproval: return "Needs approval"; case .applying: return "Applying"
        case .succeeded: return "Done"; case .failed: return "Failed"; case .cancelled: return "Cancelled"
        case .interrupted: return "Interrupted"; case .rejected: return "Rejected"; case .expired: return "Expired"
        }
    }
}

public enum RunTrigger: String, Codable, Sendable { case schedule, manual, test, resume }

public struct TokenUsage: Codable, Equatable, Sendable {
    public var input: Int
    public var cachedInput: Int
    public var output: Int
    public init(input: Int = 0, cachedInput: Int = 0, output: Int = 0) { self.input = input; self.cachedInput = cachedInput; self.output = output }
    public var total: Int { input + output }
    public static func + (a: TokenUsage, b: TokenUsage) -> TokenUsage {
        TokenUsage(input: a.input + b.input, cachedInput: a.cachedInput + b.cachedInput, output: a.output + b.output)
    }
}

/// A question the agent asked, and the answer once given.
public struct RunQuestion: Codable, Equatable, Sendable {
    public var round: Int
    public var text: String
    public var choices: [String]
    public var answer: String?
    public init(round: Int, text: String, choices: [String] = [], answer: String? = nil) {
        self.round = round; self.text = text; self.choices = choices; self.answer = answer
    }
}

/// `Automations/<id>/runs/<run-id>/run.json`. Written only by the runner, except approval fields the app sets through requests.
public struct RunRecord: Codable, Equatable, Identifiable, Sendable {
    public var id: String
    public var automationID: String
    public var automationName: String
    public var revision: Int
    public var trigger: RunTrigger
    /// The scheduled occurrence this run covers, so a clock change never repeats it.
    public var occurrence: Date?
    public var state: RunState
    public var attempt: Int
    public var queued: Date
    public var started: Date?
    public var finished: Date?
    public var exitCode: Int32?
    /// One line for rows and alerts. Never contains secrets.
    public var summary: String
    /// Plain error text when failed.
    public var error: String?
    public var usage: TokenUsage?
    /// CLI session for ask-mode resume. Created by this run only.
    public var sessionID: String?
    public var questions: [RunQuestion]
    /// File names inside the run folder.
    public var outputFile: String?
    public var proposalFile: String?
    public var journalFile: String?
    /// Runner process that owns an active run, with its start time, so a reused PID is not mistaken for it.
    public var ownerPID: Int32?
    public var ownerStart: Date?
    /// Set once the notch panel showed this run, so a relaunch does not show it again.
    public var alerted: Bool

    public init(id: String, automation: Automation, trigger: RunTrigger, occurrence: Date?, queued: Date = Date()) {
        self.id = id; self.automationID = automation.id; self.automationName = automation.name
        self.revision = automation.revision; self.trigger = trigger; self.occurrence = occurrence
        self.state = .queued; self.attempt = 1; self.queued = queued; self.summary = ""; self.questions = []; self.alerted = false
    }

    public var duration: TimeInterval? { started.flatMap { s in finished.map { $0.timeIntervalSince(s) } } }
}

public enum RunID {
    /// Sorts by time: "20260926T081500Z-3f9a".
    public static func make(at date: Date = Date()) -> String {
        let f = DateFormatter(); f.locale = Locale(identifier: "en_US_POSIX"); f.timeZone = TimeZone(identifier: "UTC")
        f.dateFormat = "yyyyMMdd'T'HHmmss'Z'"
        return f.string(from: date) + "-" + String(UUID().uuidString.prefix(4)).lowercased()
    }
    public static func isValid(_ id: String) -> Bool {
        (1...64).contains(id.count) && id.allSatisfy { $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-") }
    }
}

// MARK: Requests from the app to the runner

/// `Automations/requests/<id>.json`. The app writes; the runner reads, acts, and deletes.
public struct RunnerRequest: Codable, Equatable, Identifiable, Sendable {
    public enum Action: Codable, Equatable, Sendable {
        case runNow(automationID: String, test: Bool)
        case cancel(automationID: String, runID: String)
        case answer(automationID: String, runID: String, round: Int, text: String)
        /// Ask the agent for a new proposal with this note.
        case revise(automationID: String, runID: String, note: String)
        /// Re-read all definitions now.
        case reload
    }
    public var id: String
    public var action: Action
    public var created: Date
    public init(id: String = UUID().uuidString.lowercased(), action: Action, created: Date = Date()) {
        self.id = id; self.action = action; self.created = created
    }
}

// MARK: Shared settings the runner reads

/// `Automations/settings.json`. The app writes it; the runner reads it on each tick.
public struct AutomationSettings: Codable, Equatable, Sendable {
    public var maxConcurrentRuns: Int
    /// Days of finished runs to keep, on top of each automation's `keepRuns`.
    public var historyDays: Int
    /// Resolved CLI paths. Empty means not found.
    public var codexPath: String
    public var claudePath: String
    /// PATH given to script tasks. Set by the user, not read from a login shell.
    public var scriptPath: String
    /// Keep the Mac from idle sleep while a run is active.
    public var preventIdleSleep: Bool
    /// Claude signs in through the gateway set in `~/.claude/settings.json` (`ANTHROPIC_BASE_URL`), not the
    /// account login. Restricted mode ignores that file, so the runner passes just those values with `--settings`.
    public var claudeUsesSettingsSignIn: Bool = false
    public init(maxConcurrentRuns: Int = 2, historyDays: Int = 30, codexPath: String = "", claudePath: String = "",
                scriptPath: String = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
                preventIdleSleep: Bool = true) {
        self.maxConcurrentRuns = maxConcurrentRuns; self.historyDays = historyDays; self.codexPath = codexPath
        self.claudePath = claudePath; self.scriptPath = scriptPath; self.preventIdleSleep = preventIdleSleep
    }

    enum CodingKeys: String, CodingKey {
        case maxConcurrentRuns, historyDays, codexPath, claudePath, scriptPath, preventIdleSleep, claudeUsesSettingsSignIn
    }
    /// Older files lack newer keys; each missing key keeps its default.
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        let d = AutomationSettings()
        maxConcurrentRuns = try c.decodeIfPresent(Int.self, forKey: .maxConcurrentRuns) ?? d.maxConcurrentRuns
        historyDays = try c.decodeIfPresent(Int.self, forKey: .historyDays) ?? d.historyDays
        codexPath = try c.decodeIfPresent(String.self, forKey: .codexPath) ?? d.codexPath
        claudePath = try c.decodeIfPresent(String.self, forKey: .claudePath) ?? d.claudePath
        scriptPath = try c.decodeIfPresent(String.self, forKey: .scriptPath) ?? d.scriptPath
        preventIdleSleep = try c.decodeIfPresent(Bool.self, forKey: .preventIdleSleep) ?? d.preventIdleSleep
        claudeUsesSettingsSignIn = try c.decodeIfPresent(Bool.self, forKey: .claudeUsesSettingsSignIn) ?? false
    }
}
